DOMAIN = "satel"
DEFAULT_PORT = 7094
DEFAULT_HOST = "127.0.0.1"

CONF_USER_CODE = "user_code"
CONF_ENCRYPTION_KEY = "encryption_key"
CONF_CODE = "code"

DEFAULT_TIMEOUT = 10

CONF_ENCODING = "encoding"
DEFAULT_ENCODING = "utf-8"
