"""Constants for the Satel integration."""

DOMAIN = "satel"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 7094
DEFAULT_ENCODING = "utf-8"
DEFAULT_TIMEOUT = 10
DEFAULT_UPDATE_INTERVAL = 0
DEFAULT_RECONNECT_DELAY = 15
ENCRYPTION_METHOD_NONE = "none"
ENCRYPTION_METHODS = [ENCRYPTION_METHOD_NONE]
DEFAULT_ENCRYPTION_METHOD = ENCRYPTION_METHOD_NONE

CONF_CODE = "code"
CONF_USER_CODE = "user_code"
CONF_ENCRYPTION_KEY = "encryption_key"
CONF_ENCODING = "encoding"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_TIMEOUT = "timeout"
CONF_RECONNECT_DELAY = "reconnect_delay"
CONF_ENCRYPTION_METHOD = "encryption_method"

